// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqS0ep78oeiNJTyUVI5uPtid0jrAeBVo',
    appId: '1:923661419940:web:db82d162b6cd08d8cc2d31',
    messagingSenderId: '923661419940',
    projectId: 'cmsc23-todo-app-jbiloso-b20f5',
    authDomain: 'cmsc23-todo-app-jbiloso-b20f5.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jbiloso-b20f5.appspot.com',
    measurementId: 'G-JW7BP9XSWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHqPCrqe2drvQ5e-5lkjgiPuiRk9PtqS4',
    appId: '1:923661419940:android:cd08f06442c6b041cc2d31',
    messagingSenderId: '923661419940',
    projectId: 'cmsc23-todo-app-jbiloso-b20f5',
    storageBucket: 'cmsc23-todo-app-jbiloso-b20f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpDvlkpxKwicNC4oT6JbKkY_XqChHbPM',
    appId: '1:923661419940:ios:115e1c1b81ae163dcc2d31',
    messagingSenderId: '923661419940',
    projectId: 'cmsc23-todo-app-jbiloso-b20f5',
    storageBucket: 'cmsc23-todo-app-jbiloso-b20f5.appspot.com',
    iosClientId: '923661419940-kta606ojvr27j55r56nhdmgfnmjobn22.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFpDvlkpxKwicNC4oT6JbKkY_XqChHbPM',
    appId: '1:923661419940:ios:115e1c1b81ae163dcc2d31',
    messagingSenderId: '923661419940',
    projectId: 'cmsc23-todo-app-jbiloso-b20f5',
    storageBucket: 'cmsc23-todo-app-jbiloso-b20f5.appspot.com',
    iosClientId: '923661419940-kta606ojvr27j55r56nhdmgfnmjobn22.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
